### ISSUE TITLE
Tumblr likes dump script should avoid re-downloading a file if it already exists

### ISSUE THREAD

**Issue by catamorphism** [jonathankoren/socialdownload#7]
This might get complicated if we don't assume that posts are immutable, but I suspect the bandwidth savings from not re-downloading unchanged files exceeds the value of handling the case where a post gets edited long after it's written.

**Comment by jonathankoren** [comment]
I'm not particularly worried about immutability. I'm mostly use it to download images. `stat()`ing the destination file is probably enough.

**Comment by jonathankoren** [comment]
os.makedirs(os_path) throws an exception causing the download to be skipped if the directory already exists.
